### ISSUE TITLE
test:firefox Geckodriver don't run

### ISSUE THREAD

**Issue by Hugale12** [mucsi96/nightwatch-api#286] opened 2019-03-11 10:07 UTC
Hi everyone !

After a bug in my project i try a lot of thing and so i try to fork example project [WITHOUT CHANGE ANYTHING]
And when i run `npm run test:firefox`

i get this error : 

```powershell
> nightwatch-api-cucumber@1.0.0 test:firefox D:\Projets\Projet_Test\nightwatch-api\packages\cucumber-example
> cross-env browser=firefox npm test


> nightwatch-api-cucumber@1.0.0 test D:\Projets\Projet_Test\nightwatch-api\packages\cucumber-example
> cucumber-js --require-module babel-core/register --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty

VError: a BeforeAll hook errored, process exiting: cucumber.conf.js:6: function timed out, ensure the promise resolves within 60000 milliseconds
    at D:\Projets\Projet_Test\nightwatch-api\packages\cucumber-example\node_modules\cucumber\lib\runtime\index.js:68:19
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Projets\Projet_Test\nightwatch-api\packages\cucumber-example\node_modules\cucumber\lib\runtime\index.js:26:103)
    at _next (D:\Projets\Projet_Test\nightwatch-api\packages\cucumber-example\node_modules\cucumber\lib\runtime\index.js:28:194)
caused by: Error: function timed out, ensure the promise resolves within 60000 milliseconds
    at Timeout._time.default.setTimeout [as _onTimeout] (D:\Projets\Projet_Test\nightwatch-api\packages\cucumber-example\node_modules\cucumber\lib\user_code_runner.js:81:20)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch-api-cucumber@1.0.0 test:firefox: `cross-env browser=firefox npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightwatch-api-cucumber@1.0.0 test:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\Users\frup72768\AppData\Roaming\npm-cache\_logs\2019-03-11T09_42_04_439Z-debug.log
PS D:\Projets\Projet_Test\nightwatch-api\packages\cucumber-example>
```

Firefox version 65.0.2

```
 "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "chromedriver": "2.46.0",
    "cross-env": "^5.2.0",
    "cucumber": "^5.1.0",
    "cucumber-pretty": "^1.5.0",
    "geckodriver": "^1.15.1",
    "nightwatch": "^1.0.19",
    "nightwatch-api": "latest"
  }
```

**Comment by spnraju** [comment] 2019-03-11 16:28
Hi @Hugale12 this seems to be an issue with geckodriver. You can follow the status here. https://github.com/vladikoff/node-geckodriver/issues/18

Closing this for now.

**Comment by mucsi96** [comment] 2019-03-11 17:04
I am wondering if we can improve the error message here. Don't understand why it's just a timeout

**Comment by mucsi96** [comment] 2019-03-14 05:29
Looks like the issue is in the example

**Comment by mucsi96** [comment] 2019-03-14 05:32
Submitted a PR. For some reason if we don't enable logs for Firefox Nightwatch won't able to start it :) Looks like it's checking the output. But without enabling the logs there is no output.

**Closed** 2019-03-14 16:31 UTC
