### ISSUE TITLE
startWebDriver process keeps running

### ISSUE THREAD

**Issue by sergeisomething** [mucsi96/nightwatch-api#38] opened 2018-10-29 19:38 UTC
## Expected Behavior
Node process should be ended after tests are completed.

## Current Behavior
After updating to v1 a node process handle is being open which prevents a gulp task to be completed/closed.
Screenshot made with https://github.com/mafintosh/why-is-node-running
<img width="1080" alt="screen shot 2018-10-29 at 2 49 17 pm" src="https://user-images.githubusercontent.com/17559929/47674061-c9a8fe00-db8c-11e8-819b-b60254299dcb.png">

## Steps to Reproduce (for bugs)
1. start webdriver
2. Run gulp-cucumber
3. stop webdriver

## Context
v 0.4.0 worked fine. Current v1 is causing troubles

## Your Environment
Chromedriver 2.42.0

**Comment by mucsi96** [comment] 2018-11-18 12:32
@sergeisomething Based on the screenshot you just sent the process is not hanging in this package. But in nightwatch itself. Can you try to reproduce the issue without using this package? Looks like the issue should be fixed on nightwatch.js side. Closing for now...

**Closed by mucsi96** 2018-11-18 12:32 UTC
